# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_login_UI(object):
    def setupUi(self, login_UI):
        login_UI.setObjectName("login_UI")
        login_UI.resize(450, 300)
        login_UI.setMinimumSize(QtCore.QSize(450, 300))
        login_UI.setMaximumSize(QtCore.QSize(450, 300))
        self.centralwidget = QtWidgets.QWidget(login_UI)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        self.label1.setFont(font)
        self.label1.setTextFormat(QtCore.Qt.AutoText)
        self.label1.setObjectName("label1")
        self.gridLayout.addWidget(self.label1, 0, 0, 1, 1)
        self.useraccount = QtWidgets.QLineEdit(self.centralwidget)
        self.useraccount.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(22)
        self.useraccount.setFont(font)
        self.useraccount.setText("")
        self.useraccount.setObjectName("useraccount")
        self.gridLayout.addWidget(self.useraccount, 0, 1, 1, 1)
        self.label1_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        self.label1_2.setFont(font)
        self.label1_2.setTextFormat(QtCore.Qt.AutoText)
        self.label1_2.setObjectName("label1_2")
        self.gridLayout.addWidget(self.label1_2, 1, 0, 1, 1)
        self.userpassword = QtWidgets.QLineEdit(self.centralwidget)
        self.userpassword.setMinimumSize(QtCore.QSize(0, 37))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.userpassword.setFont(font)
        self.userpassword.setText("")
        self.userpassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.userpassword.setObjectName("userpassword")
        self.gridLayout.addWidget(self.userpassword, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.login = QtWidgets.QPushButton(self.centralwidget)
        self.login.setMaximumSize(QtCore.QSize(70, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(20)
        self.login.setFont(font)
        self.login.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.login.setObjectName("login")
        self.horizontalLayout.addWidget(self.login)
        self.verticalLayout.addLayout(self.horizontalLayout)
        login_UI.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(login_UI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 450, 23))
        self.menubar.setObjectName("menubar")
        login_UI.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(login_UI)
        self.statusbar.setObjectName("statusbar")
        login_UI.setStatusBar(self.statusbar)

        self.retranslateUi(login_UI)
        QtCore.QMetaObject.connectSlotsByName(login_UI)

    def retranslateUi(self, login_UI):
        _translate = QtCore.QCoreApplication.translate
        login_UI.setWindowTitle(_translate("login_UI", "登录"))
        self.label1.setText(_translate("login_UI", "账号："))
        self.label1_2.setText(_translate("login_UI", "密码："))
        self.login.setText(_translate("login_UI", "登录"))
